---
# run with
# docker stack deploy -c ttrss_stack.yaml ttrss
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=XXXXXXXX

  ttrss:
    image: x86dev/docker-ttrss
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - DB_ENV_PASSWORD=XXXXXXXX
      - DB_ENV_USER=postgres
      - DB_HOST=db
      - DB_NAME=ttrss
      - DB_PASSWORD=XXXXXXXX
      - DB_PORT=tcp://db:5432
      - DB_PORT_5432_TCP=tcp://db:5432
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_PORT_5432_TCP_PROTO=tcp
      - DB_USER=ttrss
      - POSTGRES_PASSWORD=XXXXXXXX
      - SELF_URL_PATH=https://ttrss.mydomain.de/
      - TTRSS_PORT=8080
      - TTRSS_SELF_URL=https://ttrss.mydomain.de/
      # - TTRSS_PROTO=http
      - TTRSS_URL=ttrss.mydomain.de
      - VIRTUAL_HOST=ttrss.mydomain.de
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=ttrss.mydomain.de
      - LETSENCRYPT_EMAIL=XXXXXXXXXXXXXXXXXX
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nextcloud/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    networks:
      - proxy-tier


  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  certs:
  conf.d:
  vhost.d:
  html:

networks:
  proxy-tier:
